### ISSUE TITLE
为什么重启redis后数据全都丢失了？

### ISSUE THREAD

**Issue by gdhzkk** [newghost/ourjs#6]
为什么重启redis后数据全都丢失了？ 发布的文章 注册的用户 全都没了？

**Comment by newghost** [comment]
我这里并没有这种情况
Redis有两种工作模式
默认是每隔一段时间(1s) 同步到硬盘一次，如果出现错误或关闭，这段时间的数据是会丢失的。
你可以设置成每个transation同步一次。不过会影响速度

**Comment by gdhzkk** [comment]
@newghost谢谢回复，我是在本地win10测试遇到的问题，第二次重启Redis后，第一次发布的文章又恢复了，但第一次重启后发布的文章又没了。
另外，关于首页不显示文章这个问题能在说明里再详细解释下嘛，还是不会弄，首页还是不显示文章。
谢谢作者开发了这么好用的程序，安装使用都很简单

**Comment by newghost** [comment]
１）首先你需要注册一个用户：　yourname
２）然后在redis为为这个用户添加管理员权限，你可以用redis_cli 或者RedisManager桌面程序来改.

```
#切换到第７个数据库（可以在config.js）里指定：　
select 7
#添加管理员权限, yourname是你注册的用户名，isAdmin是一个字段，只要有值即可
hset user:yourname  isAdmin 1
```

3)  退出并重新登录，刷新最新文章页面  http://anynb.com/new
    点击[发布]，发布你要发布的文章

**Comment by gdhzkk** [comment]
@newghost 我是在前台注册，然后和在cmd里操作后面的，但好像还是不行

**Comment by newghost** [comment]
要重新登录一次的

**Comment by gdhzkk** [comment]
@newghost 程序没有后台的嘛？还有发布文章图片只能用外链？

**Comment by newghost** [comment]
目前不支持上传图片，没有单独的管理后台。

正在开发一个独立的后台内容管理系统，可以免费使用，但是不会开源。

**Comment by gdhzkk** [comment]
@newghost 请问为什么文件 node_modules/websvr/website/web/login.htm 
会有明文用户名和密码呢？这样是否会有安全问题

**Comment by newghost** [comment]
这是测试用的示例，不会被实际使用
